# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d14d32bcc8d4a4b11df75c91920dba3e2c304b770972602d9a23bb79759072519a04e1a6382c0a3cfeeadf3ba889c965a09aa45dec80bcb0fe85bc6b6eab02aa

test:
  secret_key_base: 564b34354882bc409fcce1e24195199791ac230f4f6f92864cc92e70e5017722ab9ced53cff2405c3bacf43fa9d36bac750ee3650ac923d8904ce643277dadd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
